SRCS :=
INCS := xforms.h

default: all

all:

# begin --- Emerald interpreter targets ---

export: ../xforms.h

../xforms.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---
