.PHONY: all export clean

SRCS :=
INCS := xforms.h

all:

# begin --- Emerald interpreter targets ---

export: ../xforms.h

../xforms.h: $(INCS)
	cat $^ >$@

clean:

# end --- Emerald interpreter targets ---
