.PHONY: all export clean

SRCS :=
INCS := xliba.h

all:

# begin --- Emerald interpreter targets ---

export: ../xliba.h

../xliba.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---
