language: c
addons:
  apt:
    packages:
    - libc6-i386
    - libc6-dev-i386
    - linux-libc-dev:i386
    - libfl-dev:i386
    - gcc-multilib
    - realpath
install: make -C vmc
script: ./vmc/tests/run.sh
