matrix:
  include:
  - os: linux
    addons:
      apt:
        packages:
        - libc6-i386
        - libc6-dev-i386
        - linux-libc-dev:i386
        - libfl-dev:i386
        - gcc-multilib
        - realpath
    env:
      - EMERALDROOT=$TRAVIS_BUILD_DIR
      - EMERALDARCH=i386
      - PATH=$EMERALDROOT/bin:$PATH
      - EXTRA_CFLAGS=-m32 -Werror
  - os: linux
    addons:
      apt:
        packages:
        - libc6
        - libc6-dev
        - linux-libc-dev
        - libfl-dev
        - gcc-multilib
        - realpath
    env:
      - EMERALDROOT=$TRAVIS_BUILD_DIR
      - EMERALDARCH=i686
      - PATH=$EMERALDROOT/bin:$PATH
      - EXTRA_CFLAGS=-Werror
install:
  - make -C vmc
  - emmake -C ccalls
script: ./vmc/tests/run.sh
