.PHONY: all export clean

SRCS := hello.c
INCS := hello.h exit.h

all:

# begin --- Emerald interpreter targets ---

export: ../misc.h

../misc.h: $(INCS)
	cat $^ >$@

clean:

# end --- Emerald interpreter targets ---
