.PHONY: all export clean

SRCS :=
INCS := random.h

all:

# begin --- Emerald interpreter targets ---

export: ../trandom.h

../trandom.h: $(INCS)
	cat $^ > $@

clean:

# end --- Emerald interpreter targets ---
