.PHONY: all export clean

SRCS :=
INCS := bani.h

all:

# begin --- Emerald interpreter targets ---

export: ../bani.h

../bani.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---
