.PHONY: all export clean

SRCS :=
INCS := misk.h

all:

# begin --- Emerald interpreter targets ---

export: ../misk.h

../misk.h: $(INCS)
	cat $^ >$@

clean:

# end --- Emerald interpreter targets ---
