.PHONY: default all export clean

SRCS :=
INCS := rand.h

default: all

all:

# begin --- Emerald interpreter targets ---

export: ../rand.h

../rand.h: $(INCS)
	cat $^ >$@

clean:

# end --- Emerald interpreter targets ---
