#!/bin/csh -f
ed - << theend
0r vmcpar.y
v/^%token/d
1,\$s;%token *	*\([^ 	]*\).*/\* ;	/* \1 */	;
1,\$s; *\*/[ 	]*\$;,;
\$s/,\$//
1i
char *tokenNameTable[] = {
	/* none */	"",
.
\$a
};
.
w tokNames.c
q
theend
